### ISSUE TITLE
skill section overlaps

### ISSUE THREAD

**Issue by aseerkt** [amand33p/amand33p.github.io#2]
For my PC viewport of 1366x768. The title of skills section overlaps with the hero section.
![amand](https://user-images.githubusercontent.com/39845171/114300832-ad407800-9adf-11eb-92d5-6ecb3af14fec.png)

**Comment by amand33p** [comment]
@aseerkt On which browser? It works fine for me on FireFox. 🤔

Edit: It works fine even on chrome for me.

**Comment by aseerkt** [comment]
Did you tried zooming in?.

**Comment by amand33p** [comment]
@aseerkt Why would I try zooming? 🤔🤔

Isn't responsiveness done for 100% zoom?! Anyways, send full browser screenshot.

**Comment by aseerkt** [comment]
![Uploading amand33p.github.io_.png…]()

**Comment by aseerkt** [comment]
![amand33p github io_](https://user-images.githubusercontent.com/39845171/114301807-eb3f9b00-9ae3-11eb-9ac1-4c80367647bb.png)

**Comment by amand33p** [comment]
@aseerkt Nice screenshot! Now tell me how did you take it? What browser, dimensions etc. I'm not able to recreate it, unfortunately.

**Comment by aseerkt** [comment]
I use chrome. I don't know if its specific to my system. I used chrome devtools to take screenshot from the responsive tab.
![responsive-tab-amand](https://user-images.githubusercontent.com/39845171/114302106-3a3a0000-9ae5-11eb-8345-55a0f93d8f06.png)
 responsive tab. 1030x541

**Comment by amand33p** [comment]
@aseerkt That's really strange, mate. I'm using the same to recreate it.

Check my screenshot.

[
![Screenshot (4)](https://user-images.githubusercontent.com/47207763/114302123-4faf2a00-9ae5-11eb-95de-cfa5d3c1d9f0.png)
](url)

**Comment by amand33p** [comment]
@aseerkt Ahh, got it. You're using an unnatural screen size. 1030 x 541. I made my site responsive to only the valid screens. :(
